### ISSUE TITLE
Can no longer connect to Xfinity Home

### ISSUE THREAD

**Issue by fitzage** [nfarina/homebridge-icontrol#1]
A few days ago, homekit stopped connecting to Xfinity Home via Homebridge. I then started having issues with other accessories not showing up in the Home app, although oddly enough Siri could still sometimes work with them.

So I went in and did some upgrades and such, and didn't actually try manually running homebridge until I got all that stuff done. Everything else works, but if I try to enable iControl for Xfinity Home, I get this.

```
[5/1/2017, 8:50:42 PM] Loading 1 accessories...
[5/1/2017, 8:50:42 PM] [Xfinity Home] Initializing iControl accessory...
[5/1/2017, 8:50:43 PM] [Xfinity Home] Logging into iControl...
/usr/local/lib/node_modules/homebridge-icontrol/node_modules/node-icontrol/index.js:199
      var action = actionRegex.exec(body)[1]; // i.e. https://login.comcast.net/login
                                         ^

TypeError: Cannot read property '1' of null
    at iControl.<anonymous> (/usr/local/lib/node_modules/homebridge-icontrol/node_modules/node-icontrol/index.js:199:42)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-icontrol/node_modules/request/request.js:373:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-icontrol/node_modules/request/request.js:1318:14)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-icontrol/node_modules/request/request.js:1266:12)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:921:12)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
```

**Comment by nfarina** [comment]
Yeah, unfortunately I've been having this same issue since reinstalling homebridge on my upgraded Raspberry Pi, and haven't figured out the root cause yet. It's bizarre - the HTTP responses from iControl are the same, but the `Request` library isn't returning the full HTTP body. I spent some time on it but it's tough to debug because it doesn't happen on my laptop, only on my RPi.

**Comment by fitzage** [comment]
So basically this is only happening because I'm running on a Raspberry Pi? :-)

I suppose you haven't figured out yet if there's some kind of combination of node/module/etc versions that doesn't have this problem, then.

**Comment by fitzage** [comment]
Man, looks like that's the only way to connect Xfinity Home to HomeKit, too. Dangit.

**Comment by nfarina** [comment]
Yeah, I can't think of what to try next besides just using a different request library. But it will be some work swapping it out.

**Comment by vidvisionify** [comment]
I hope you're able to get this fixed soon! I started using Home Assistant/Homebridge and I was hoping to integrate my current security system!

**Comment by fitzage** [comment]
Yeah, this feature is really what takes this from "pretty cool and handy," to "absolutely amazing" for my use cases.

**Comment by nfarina** [comment]
Well the good news is that I can reproduce it on my laptop now - so a fix should be more doable. Investigating now.

**Comment by nfarina** [comment]
Better news - I've gotten it working again! Added a workaround for the request library weirdness, and also updated the iControl REST API endpoints which had changed. Give the new release a shot and let me know if it works!

**Comment by fitzage** [comment]
Success!

**Comment by fitzage** [comment]
It worked at first, then HomeKit stopped being able to update the status of the security system. The only way I figured out how to fix that was delete the entire homebridge accessory and start over, but that didn't last long. It seems to be related to these errors.

```
Jun 01 21:03:48 raspberrypi homebridge[18896]: at emitOne (events.js:77:13)
Jun 01 21:03:48 raspberrypi homebridge[18896]: at TLSSocket.emit (events.js:169:7)
Jun 01 21:03:48 raspberrypi homebridge[18896]: at readableAddChunk (_stream_readable.js:153:18)
Jun 01 21:03:48 raspberrypi homebridge[18896]: at TLSSocket.Readable.push (_stream_readable.js:111:10)
Jun 01 21:03:48 raspberrypi homebridge[18896]: at TLSWrap.onread (net.js:536:20)
Jun 01 21:03:48 raspberrypi homebridge[18896]: Response:
Jun 01 21:03:48 raspberrypi homebridge[18896]: undefined
```

**Comment by nfarina** [comment]
Can you post more of the surrounding log data?

**Comment by fitzage** [comment]
Yeah, shouldn't have been doing this on my phone.

```
Jun 01 21:17:26 raspberrypi homebridge[18896]: [6/1/2017, 9:17:26 PM] [Xfinity Home] There was an error while communicating with iControl. Status code was undefined and errorJun 01 21:17:26 raspberrypi homebridge[18896]: Stack:Error
Jun 01 21:17:26 raspberrypi homebridge[18896]: at iControl._notifyError (/usr/local/lib/node_modules/homebridge-icontrol/node_modules/node-icontrol/index.js:500:181)
Jun 01 21:17:26 raspberrypi homebridge[18896]: at iControl.<anonymous> (/usr/local/lib/node_modules/homebridge-icontrol/node_modules/node-icontrol/index.js:233:16)
Jun 01 21:17:26 raspberrypi homebridge[18896]: at self.callback (/usr/local/lib/node_modules/homebridge-icontrol/node_modules/node-icontrol/node_modules/request/request.js:18Jun 01 21:17:26 raspberrypi homebridge[18896]: at emitOne (events.js:77:13)
Jun 01 21:17:26 raspberrypi homebridge[18896]: at Request.emit (events.js:169:7)
Jun 01 21:17:26 raspberrypi homebridge[18896]: at Request.init (/usr/local/lib/node_modules/homebridge-icontrol/node_modules/node-icontrol/node_modules/request/request.js:460Jun 01 21:17:26 raspberrypi homebridge[18896]: at Redirect.onResponse (/usr/local/lib/node_modules/homebridge-icontrol/node_modules/node-icontrol/node_modules/request/lib/redJun 01 21:17:26 raspberrypi homebridge[18896]: at Request.onRequestResponse (/usr/local/lib/node_modules/homebridge-icontrol/node_modules/node-icontrol/node_modules/request/rJun 01 21:17:26 raspberrypi homebridge[18896]: at emitOne (events.js:77:13)
Jun 01 21:17:26 raspberrypi homebridge[18896]: at ClientRequest.emit (events.js:169:7)
Jun 01 21:17:26 raspberrypi homebridge[18896]: at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:433:21)
Jun 01 21:17:26 raspberrypi homebridge[18896]: at HTTPParser.parserOnHeadersComplete (_http_common.js:103:23)
Jun 01 21:17:26 raspberrypi homebridge[18896]: at TLSSocket.socketOnData (_http_client.js:322:20)
Jun 01 21:17:26 raspberrypi homebridge[18896]: at emitOne (events.js:77:13)
Jun 01 21:17:26 raspberrypi homebridge[18896]: at TLSSocket.emit (events.js:169:7)
Jun 01 21:17:26 raspberrypi homebridge[18896]: at readableAddChunk (_stream_readable.js:153:18)
Jun 01 21:17:26 raspberrypi homebridge[18896]: at TLSSocket.Readable.push (_stream_readable.js:111:10)
Jun 01 21:17:26 raspberrypi homebridge[18896]: at TLSWrap.onread (net.js:536:20)
Jun 01 21:17:26 raspberrypi homebridge[18896]: Response:
Jun 01 21:17:26 raspberrypi homebridge[18896]: undefined
```

**Comment by mdzwolf** [comment]
I have just installed this plugin on my raspberry pi and I am getting the same issue about 
/usr/local/lib/node_modules/homebridge-icontrol/node_modules/node-icontrol/index.js:199
      var action = actionRegex.exec(body)[1]; // i.e. https://login.comcast.net/login
                                         ^

TypeError: Cannot read property '1' of null

Did something else change?

**Comment by nfarina** [comment]
Sorry guys, I switched to Nest Secure when it came out and ditched Xfinity Home. I was never able to figure out why the request library wasn't working with their API. Happy to accept PRs though if someone can crack it!
